all:
  hosts:
    k8s-00:
      ansible_host: 10.10.10.202
      ansible_user: rojo
    k8s-01:
      ansible_host: 10.10.10.253
      ansible_user: rojo
    k8s-02:
      ansible_host: 10.10.10.215
      ansible_user: rojo
  children:
    k8s:
      hosts:
        k8s-00:
        k8s-01:
        k8s-02:
